name: CI/CD for React Frontend

on:
  push:
    branches: [ "Zakariae_Branch", "Hamza_Branch", "Abdo_Branch" ]
  pull_request:
    branches: [ "Zakariae_Branch", "Hamza_Branch", "Abdo_Branch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build
